---
- name: Download wp-cli
  get_url:
    url: "{{ wordpress_wpcli_url }}"
    dest: /usr/local/bin/wp-cli
    mode: 0755

- name: Template Wordpress Nginx config
  template:
    src: nginx_server.conf
    dest: /etc/nginx/sites-available/{{ wordpress_hostname }}

- name: Check certbot certs exist
  stat:
    path: /etc/letsencrypt/live/{{ wordpress_hostname }}
  register: certbot

- name: Permission certs so nginx can read them
  file:
    mode: 0774
    path: "{{ item }}"
    group: www-data
    recurse: yes
  with_items:
    - /etc/letsencrypt/archive
    - /etc/letsencrypt/live

- name: Create site directories
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ wordpress_install_path }}"
    - "{{ wordpress_page_cache_path }}"

- name: Download Wordpress
  command: >
    wp-cli core download
    --allow-root --no-color --path='{{ wordpress_install_path }}'
    --locale='{{ wordpress_locale }}'
  args:
    creates: "{{ wordpress_install_path }}/index.php"

- name: Generate wp-config.php
  command: >
    wp-cli core config
    --allow-root --no-color --path='{{ wordpress_install_path }}'
    --dbname={{ wordpress_database_name }} --dbuser={{ wordpress_database_username }} --dbpass={{ wordpress_database_password }}
  args:
    creates: "{{ wordpress_install_path }}/wp-config.php"

- name: Install Wordpress
  command: >
    wp-cli core install
    --allow-root --no-color --path='{{ wordpress_install_path }}'
    --url='{{ wordpress_url }}' --title='{{ wordpress_site_title }}'
    --admin_name='{{ wordpress_admin_username }}'
    --admin_email='{{ wordpress_admin_email }}'
    --admin_password='{{ wordpress_admin_password }}'

- name: Disable Wordpress Cron
  command: >
    wp-cli
    --allow-root --no-color --path='{{ wordpress_install_path }}'
    config set DISABLE_WP_CRON true --raw

- name: Enable cron via system cron.d
  cron:
    name: "Wordpress Cron"
    minute: "5"
    job: "/usr/local/bin/wp-cli --allow-root --no-color --path='{{ wordpress_install_path }}' cron event run --due-now >/dev/null 2>&1"

- name: Install plugins
  command: >
    wp-cli --allow-root --no-color --path='{{ wordpress_install_path }}'
    plugin install {{ item }}
  with_items: "{{ wordpress_plugins }}"

- name: Enable site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ wordpress_hostname }}
    dest: /etc/nginx/sites-enabled/{{ wordpress_hostname }}
    state: link
  register: site_symlink

- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded
  when: site_symlink.changed