---
- name: Set a hostname
  hostname:
    name: "{{ os_hostname }}"

- name: Set timezone
  timezone:
    name: "{{ os_timezone }}"

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  when: os_update_packages == true

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes